version: '3'

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./assets/redis_data:/data
    network_mode: host
  redis_test:
    image: redis:7-alpine
    ports:
      - 6380:6379
