name: CMake

on:
  push:
    branches: [ "master", "unit_tests" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_WITH_QT=OFF -DBUILD_WITH_REDIS=ON

    - name: Build unit tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target unit_tests

    - name: Run unit test
      working-directory: ${{github.workspace}}/build
      run: ./unit_tests

    - name: Build integration tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target integration_tests

    - name: Run integration tests
      run: docker compose up --no-TTY integration_tests
